---
- name: apt
  apt: upgrade=full
- apt: pkg={{item}}
  with_items:
  - ntp
  - dstat
  - mosh
  - byobu
  - htop
  - secure-delete
  - unattended-upgrades
- lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no"
- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic
- name: user mlin
  user: name=mlin shell=/bin/bash uid=1861
- stat: path=/home/mlin/.ssh/authorized_keys
  register: authorized_key_exists
- authorized_key: user=mlin key="{{ lookup('file', '/home/ubuntu/.ssh/authorized_keys') }}"
  when: not authorized_key_exists
- lineinfile: dest=/etc/sudoers.d/50-mlin create=yes line="mlin ALL=(ALL) NOPASSWD:ALL"
- file: path=/etc/sudoers.d/50-mlin owner=root group=root mode=0440
- shell: sudo -H -u mlin bash -ex -c "yes '' | byobu-enable" || true
- name: disable default ubuntu user account
  user: name=ubuntu state=absent remove=yes force=yes
- group: name=ubuntu state=absent
- file: path=/etc/sudoers.d/90-cloudimg-ubuntu state=absent
- name: x2go
  apt_repository: repo='ppa:x2go/stable'
- name: desktop packages
  apt: pkg={{item}}
  with_items:
  - x2goserver
  - x2goserver-xsession
  - xfce4
  - xfce4-terminal
  - firefox
