---
- name: apt
  apt: upgrade=full
- apt: pkg={{item}}
  with_items:
  - vim
  - ntp
  - mosh
  - byobu
  - unattended-upgrades
  - htop
  - dstat
  - secure-delete
  - build-essential
  - git
  - python-pip
  - python3-pip
  - docker.io
  - pv
  - jq
  - pigz
  - tree
  - openjdk-11-jre-headless
- lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no"
- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic
- name: user mlin
  user: name=mlin shell=/bin/bash uid=1861
- authorized_key: user=mlin key="{{ lookup('file', '/home/ubuntu/.ssh/authorized_keys') }}"
- lineinfile: dest=/etc/sudoers.d/50-mlin create=yes line="mlin ALL=(ALL) NOPASSWD:ALL"
- file: path=/etc/sudoers.d/50-mlin owner=root group=root mode=0440
- name: docker group
  command: gpasswd -a mlin docker
- shell: sudo -H -u mlin bash -ex -c "yes '' | byobu-enable" || true
- name: pip packages
  executable: pip3
  pip: name="{{item}}"
  with_items:
  - awscli
- name: additional apt repositories
  apt_repository: repo="{{item}}"
  with_items:
  - ppa:x2go/stable
- name: desktop packages
  apt: pkg={{item}}
  with_items:
  - xubuntu-desktop
  - x2goserver
  - x2goserver-xsession
  - openvpn
- name: disable default ubuntu user account
  command: chage -E 0 ubuntu
- file: path=/etc/sudoers.d/90-cloudimg-ubuntu state=absent
