---
- name: several apt packages
  apt: pkg={{item}}
  with_items:
  - ntp
  - dstat
  - mosh
  - byobu
  - htop
  - secure-delete
  - unattended-upgrades
- lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no"
- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic
